on:
  rss:
    url: https://hnrss.org/newest?points=300&count=3
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
      - name: create-json
        id: create-json  # Second ID
        uses: jsdaniell/create-json@v1.1.2
        with:
          name: "other.json"
          json: '{"name":$title, "link":$link}'
          dir: '/src'
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a || echo "No changes to commit"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
